# 設定 global 全域設定
# scrape_interval 是多久抓取一次資料
global:
    scrape_interval: 5s
    external_labels:
      monitor: 'demo-monitor'

# scrape_configs 則是抓取來源
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  scrape_timeout: 3s
  metrics_path: /metrics
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'api_monitor'
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  params:
    format: [ prometheus ]
  static_configs:
    - targets: ['api:8000']

- job_name: 'cadvisor'
  static_configs:
  - targets: ['cadvisor:8080']
